baseURL = 'https://blog.rahulkonduru.com/'
languageCode = 'en-us'
title = 'Rahul Konduru Blog'
theme = 'loveit'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[author]
    name = "Rahul Konduru"