baseURL = 'https://blog.rahulkonduru.com/'
languageCode = 'en-us'
title = "Rahul Konduru's Blog"
theme = 'loveit'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[params]
    defaultTheme = "light"
    title = "Rahul Konduru's Blog"  
    description = "Welcome to my tech blog."
    [params.author]
        name = 'Rahul Konduru'
        link = 'https://blog.rahulkonduru.com'
    [params.header]
    [params.header.title]
      # title name
      name = "Rahul Konduru"
      # LoveIt NEW | 0.2.5 whether to use typeit animation for title name
      typeit = false

    [params.app]
        # optional site title override for the app when added to an iOS home screen or Android launcher
        title = "Rahul Konduru's Blog"
    
    [params.home]
        # LoveIt NEW | 0.2.0 amount of RSS pages
        rss = 10
        # Home page profile
        [params.home.profile]
            enable = true
            # URL of avatar shown in home page
            # avatarURL = "/images/avatar.png"
            # LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
            title = "Rahul Konduru's tech blog"
            # subtitle shown in home page (HTML format is supported)
            subtitle = "Welcome to my tech blog."

[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""

# Sitemap config
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5